Add TryAsync and extensions for Tasks of Result
LazyBallsZealots/Results.Immutable pull request #44
Opened 2023-11-03 19:27 UTC by mtyski

2023-11-05 15:28 UTC, ricksanchez requested changes

2023-11-05 15:28 UTC, ricksanchez commented on src/Results.Immutable/Extensions/TaskOfResultExtensions.cs
> +    public static async Task<Result<TNew>> SelectMany<T, TIntermediate, TNew>(
I am not sure if this function is needed, the user may use the next override or simply await the result so they won't have to deal with async anymore.

2023-11-05 15:28 UTC, ricksanchez commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +        static Task<Result<int>> RunSecondTask(int _) => Task.FromResult(Result.Ok(finalValue));
Can you use the value? it may help to identify possible issues, at this point `_` may equal `0` (`default`).

2023-11-05 15:28 UTC, ricksanchez commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +        .Be(Result.Ok());
The same here, use the values to verify the methods are passing them properly

2023-11-05 15:28 UTC, ricksanchez commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +    [Fact(DisplayName = "Projecting a failed result should return a new, equivalent result without ")]
Remove trailing space

2023-11-05 15:28 UTC, ricksanchez commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +public sealed class TaskOfResultExtensionsTests
In other test files we are using the format `Does....`. Please use it here.

2023-11-05 15:28 UTC, ricksanchez commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +    public async Task NoOpProjectionOfMultipleAsyncResultsShouldReturnResultOfUnit() =>
Please add a test similar to this one with query syntax. To ensure it is recognized by the compiler.

2023-11-06 17:51 UTC, mtyski commented on src/Results.Immutable/Extensions/TaskOfResultExtensions.cs
> +    public static async Task<Result<TNew>> SelectMany<T, TNew>(
- Changed `Select` to use synchronous selector (in line with LINQ for async enumerables).
- Changed `SelectMany` to use asynchronous selectors exclusively (as it will probably be the most common use-case).

2023-11-06 17:52 UTC, mtyski commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +        static Task<Result<int>> RunSecondTask(int _) => Task.FromResult(Result.Ok(finalValue));
Updated FsCheck and used property tests in a similar manner to the synchronous counterparts.

2023-11-06 17:53 UTC, mtyski commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +public sealed class TaskOfResultExtensionsTests
Renamed to `AsyncProjectionsTests`

2023-11-06 17:53 UTC, mtyski commented on src/Results.Immutable.Tests/ExtensionsTests/TaskOfResultExtensionsTests.cs
> +    [Fact(DisplayName = "Projecting a failed result should return a new, equivalent result without ")]
Should be gutted now (dunno why the pre-commit hooks blew up 😅 )

2023-11-07 19:01 UTC, ricksanchez approved these changes
LGTM

2023-11-07 19:03 UTC, merged