Add sync-to-async projections for generic ValueTasks
LazyBallsZealots/Results.Immutable pull request #54
Opened 2024-01-30 17:53 UTC by mtyski

2024-02-02 20:47 UTC, ricksanchez requested changes

2024-02-02 20:47 UTC, ricksanchez commented on src/Results.Immutable/Projections/Result/Select.cs
> +    public async ValueTask<Result<TNew>> Select<TNew>(Func<T, ValueTask<TNew>> asyncSelector) =>
I think `Select` should not change the structure, only the value, this can be called `SelectAsync` to indicate the structure change `Result<T> -> ValueTask<Result<TNew>>`

Did you test this overload with query syntax?

2024-02-02 20:47 UTC, ricksanchez commented on src/Results.Immutable/Projections/Result/SelectMany.cs
> +    public async ValueTask<Result<TNew>> SelectMany<TIntermediate, TNew>(
Also for this functions, I suspect it is better to keep the structure or rename the methods to something ...Async to indicate the conversion to a task.

If this is for query syntax, and if it works, it can be ok. Since it is not consider code for humans, rather for the compiler.

2024-02-02 23:35 UTC, mtyski commented on src/Results.Immutable/Projections/Result/SelectMany.cs
> +    public async ValueTask<Result<TNew>> SelectMany<TIntermediate, TNew>(
Renamed to `SelectManyAsync`

2024-02-02 23:36 UTC, mtyski commented on src/Results.Immutable/Projections/Result/Select.cs
> +    public async ValueTask<Result<TNew>> Select<TNew>(Func<T, ValueTask<TNew>> asyncSelector) =>
Renamed to `SelectAsync`

2024-02-03 19:04 UTC, ricksanchez approved these changes
LGTM

2024-02-03 21:00 UTC, merged