feat: add fluent assertions extensions for result immutable
LazyBallsZealots/Results.Immutable pull request #60
Opened 2024-03-11 21:07 UTC by ricksanchez

2024-03-11 23:00 UTC, mtyski requested changes

2024-03-12 20:41 UTC, ricksanchez commented on src/Results.Immutable.Extensions.FluentAssertions.Tests/GlobalUsings.cs
we should refactor the other file, GlobalUsings is what MS templates give out of the box.

2024-03-14 20:14 UTC, ricksanchez commented on src/Results.Immutable.Extensions.FluentAssertions/Assertions/ResultAssertions.cs
I suggest to keep it open for inheritance outside this project

2024-03-14 20:53 UTC, ricksanchez commented on src/Results.Immutable.Extensions.FluentAssertions/Assertions/ResultAssertions.cs
> +                typeof(TError));
nameof returns `"TError"` which is useless, an alternative is `typeof(TError).Name` but I prefer the fully qualified, in case there are many classes with the same name.

2024-03-14 20:59 UTC, ricksanchez commented on src/Results.Immutable.Extensions.FluentAssertions/Assertions/ResultAssertions.cs
> +    public AndWhichConstraint<ResultAssertions<T>, TError> ContainErrorOfType<TError>(
I renamed and changed the type, the message checking and others can bye done via `.Which` or via `.BeEquivalentTo` as well.

2024-04-01 13:48 UTC, mtyski approved these changes
LGTM!

2024-04-01 13:51 UTC, merged