feat: add `.Where` and `.WhereAsync` for `Result`
LazyBallsZealots/Results.Immutable pull request #75
Opened 2024-05-09 20:58 UTC by ricksanchez

Allow filtering the result and in case it is filtered out allow to give errors

2024-05-11 14:26 UTC, mtyski requested changes

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
>  }
Those are not property tests; change attributes to `Fact`s instead

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +            .Be(new Error("epic"));
The passed `Error` instance can be extracted to a variable.

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +            .Be(new Error("abysmal"));
Same here; created error can be declared as a variable.

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +            .Be(new Error("epic"));
Either declare the collection as a variable and assert on the equivalency of the initial collection and the actual errors, or declare the error as a variable and use a trick similar to this:

```CSharp
Result.Ok(0)
    .Where(
        static x => x > 0,
        new[] { error, })
    .Errors
    .Should()
    .SatisfyRespectively(
        singleError => singleError.Should()
            .Be(error));
```

...with the first solution being preferrable due to readability.

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +            .Be(new Error("epic"));
Same here; collection into a variable and assert on equivalency or single member to variable and `SatisfyRespectively()`.

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +            .WhereAsync(static x => ValueTask.FromResult(x > 0), new Error("irrelevant")))
I'd probably assign this to a variable, but as-is is also relatively fine.

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +            .WhereAsync(static x => ValueTask.FromResult(x > 0), new Error("epic")))
Similarly here; `await`ed task to a variable makes deciphering this easier.

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ResultProjectionTests.cs
> +        .Be(new Error("epic"));
`await`ed task to a variable, collections assertions... Basically: combine previous suggestions

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable/Projections/Result/SelectMany.cs
> +                    .ToImmutableList());
Those are not projections; they are filters (these should get their own directory and their own file inside that)

2024-05-11 14:26 UTC, mtyski commented on src/Results.Immutable/Projections/Result/SelectManyAsync.cs
> +                    .ToImmutableList());
Same here; separate into another class in the same directory sync filter will go.

EDIT: check the `inheritdoc`, as I'm almost certain specific parameters that were not properly documented in original method do NOT get the docs

2024-05-14 17:52 UTC, mtyski reviewed
This is the only thing I found for now; in the future we might wanna provide feature parity for `Option<>`, but that can simply be an issue we will address at a later date.

2024-05-14 17:52 UTC, mtyski commented on src/Results.Immutable/Filters/Result/Where.cs
> +        Some is var (value) && await predicate(value) ? this : new(ImmutableList.Create(errorFactory()));
Current implementations all suffer from the same issue: we're losing error references from the original result;
In order to keep them (even as nested errors), we'd have to do the following:

```CSharp
var result = SomeOperationReturningResult();

return result.Where(SomePredicate, new Error("Predicate failed!", result.Errors));
```

We might wanna remove the overloads that only accept `Error` instances and instead provide sth akin to the following:
```CSharp
public Result<T> Where(
    Func<T, bool> predicate,
    Func<IEnumerable<Error>, Error> errorsFactory) =>
    Some is var (value) && predicate(value) ? this : new(errorsFactory(Errors));
```

The usage would be slightly streamlined:
```CSharp
return SomeOperationReturningResult()
    .Where(
        SomePredicate
        errors => new Error("Predicate is not fulfilled!", errors));
```

This can be another overload as well (but then we need to add to remarks that methods `Where(Func<T, bool>, Error)` and `Where(Func<T, bool>, Func<Error>)` will cause potential data loss).

2024-05-14 18:59 UTC, ricksanchez commented on src/Results.Immutable/Filters/Result/Where.cs
> +        Some is var (value) && await predicate(value) ? this : new(ImmutableList.Create(errorFactory()));
ok, there is an issue here to cover, that's also not the expected behavior.

It should be `failed.Where(falseFn, anyError) == failed`

2024-05-14 19:27 UTC, mtyski approved these changes

2024-05-14 19:33 UTC, merged