EachParser
LazyBallsZealots/Results.Immutable pull request #81
Opened 2024-06-09 19:58 UTC by ricksanchez

- Require AoT
- Allow to transpose more types
- add xml documentation in static result
- ParseEach

2024-06-10 20:52 UTC, mtyski requested changes

2024-06-10 20:52 UTC, mtyski commented on src/Results.Immutable/Factories/ResultFactories.cs
> +    /// <param name="condition">Condition to check.</param>
Adding these blocks renders `<inheritdoc cref="" />` instructions no longer required.

2024-06-10 20:52 UTC, mtyski commented on src/Results.Immutable/Member/EachParser.cs
> +        string message = "")
Instead of an optional message, I believe we can instead pass here a `Func<TElement, int, Error>`, to instantiate specific errors, rather than represent that sth is wrong with an element under a specific index. This makes a lot more sense in the context of unordered collections (like sets).

2024-06-10 20:52 UTC, mtyski commented on src/Results.Immutable.Tests/MemberTests/EachParserTests.cs
> +        var result = (await new[]
Either assign this to discard, or keep the variable as a way to hold result of the `ValueTask<Result<T>>`.

2024-06-17 07:40 UTC, mtyski commented on src/Results.Immutable/Member/EachParser.cs
> +        }
We can abuse quirks of the compiler here (lambda expressions awaiting `ValueTask`s are `Task`s and `ValueTask`s at the same time for the sake of type-checking):

```suggestion
        var results = await Task.WhenAll(
            values.Select(
                async (x, i) =>
                {
                    var result = await parser(x);
                    return result is { Errors: { IsEmpty: false } errors } ?
                        Result.Fail<TParsed>(createError(x, i, errors)) :
                        result;
                }));
```

2024-06-17 07:41 UTC, mtyski reviewed
One last bit to improve, as sequential task execution can be worked around

2024-06-17 19:52 UTC, ricksanchez commented on src/Results.Immutable/Member/EachParser.cs
> +        }
I partially applied your solution, take in mind that using `Error.IsEmpty` may produce an unnecessary allocation if there is no error. It is more efficient to use `.Some`.

2024-06-24 09:00 UTC, mtyski reviewed
Last batch of changes, mostly stylistic

2024-06-24 09:00 UTC, mtyski commented on src/Results.Immutable/Member/EachParser.cs
> +                    return result.Some is { }
Same here - `is not null` is an option

2024-06-29 07:53 UTC, mtyski approved these changes

2024-06-29 07:53 UTC, mtyski approved these changes

2024-06-29 07:54 UTC, merged