Add error projections
LazyBallsZealots/Results.Immutable pull request #88
Opened 2024-07-07 12:09 UTC by mtyski

Should be merged after #87

Adds following projections for errors:

- `SelectErrors` projects all errors associated with the result.
- `SelectManyErrors` combines all errors into one (should be used in conjunction with `Error.WithRootCauses`).

2024-07-21 17:27 UTC, ricksanchez commented on src/Results.Immutable/Projections/Result/SelectErrors.cs
> +    public Result<T> SelectErrors<TError>(Func<Error, TError> errorSelector)
I believe the right signature should be `Func<ImmutableList<Error>, ImmutableList<Error>>`, I don't think we should map each element of the list because the error part should be seen as one

2024-07-21 17:28 UTC, ricksanchez commented on src/Results.Immutable/Projections/Result/SelectErrors.cs
> +    public Result<T> SelectManyErrors<TError>(Func<ImmutableList<Error>, TError> errorsCombinator)
I am not sure if this method if `SelectErrors` has the said signature, LINQ `SelectMany` can be combined with it.

2024-07-21 17:30 UTC, ricksanchez commented on src/Results.Immutable/Projections/Result/SelectErrors.cs
> +    public Result<T> SelectErrors<TError>(Func<Error, TError> errorSelector)
Also, we don't need a generic parameter, because the `Error` is always used, and never another type of error is known in the `Result<T>` type.

2024-07-21 19:20 UTC, mtyski commented on src/Results.Immutable/Projections/Result/SelectErrors.cs
> +    public Result<T> SelectErrors<TError>(Func<Error, TError> errorSelector)
In general, I aimed for this to be a convenience method around the following snippet:

```csharp
originalResult.HasFailed ?
    Result.Fail(originalResult.Errors.Select(/* snip */)) :
    originalResult;
```

I'd rather preserve this signature, to be honest, as the list-to-list conversion is definitely not widely used in C#; pretty much all LINQ methods work with single objects (with notable exceptions of `.Aggregate()` and `.Zip()`, from the top of my head).

2024-07-21 19:21 UTC, mtyski commented on src/Results.Immutable/Projections/Result/SelectErrors.cs
> +    public Result<T> SelectManyErrors<TError>(Func<ImmutableList<Error>, TError> errorsCombinator)
Renamed to `.AggregateErrors()` to better reflect the intended use case.

2024-07-21 19:24 UTC, mtyski commented on src/Results.Immutable/Projections/Result/SelectErrors.cs
> +    public Result<T> SelectErrors<TError>(Func<Error, TError> errorSelector)
Good catch :+1: 

Removed the parameter and adjusted the docs.

2024-08-17 07:16 UTC, ricksanchez requested changes

2024-08-17 07:16 UTC, ricksanchez commented on src/Results.Immutable.Tests/ResultTests/ErrorProjectionTests.cs
> +    [Fact(DisplayName = "MergeErrorsWith on a failed result combinbes all top-level errors")]
combines* small typo

2024-08-17 19:47 UTC, mtyski commented on src/Results.Immutable.Tests/ResultTests/ErrorProjectionTests.cs
> +    [Fact(DisplayName = "MergeErrorsWith on a failed result combinbes all top-level errors")]
Good catch! Fixed.

2024-08-18 16:45 UTC, ricksanchez approved these changes

2024-08-18 16:45 UTC, merged